### ISSUE TITLE
Handling sensitive variables (sensitive = true)

### ISSUE THREAD

**Issue by hongkongkiwi** [tcarreira/terraform-provider-env#11]
Is it possible to add a "sensitive" boolean to this? Just like in the variable block. This means that the value would not be output to the screen during plans.

```
data "env_var" "test" {
  id       = "TF_VAR_client_id"
  required = true
  sensitive = true
}
```

The reason for this is to be able to dynamically bring in variables based on some other value e.g. 
```
data "env_var" "test" {
  for_each = var.secrets
  id       = "TF_VAR_${each.key}"
  required = true
  sensitive = true
}
```

**Comment by tcarreira** [comment]
Hi @hongkongkiwi 
That seams like a nice idea.

Unfortunately, as per [documentation](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/attributes/set#sensitive) `This setting cannot be conditionally set`

But I could add a different resource `env_sensitive` :
```
data "env_sensitive" "test" {
  id       = "TF_VAR_client_id"
  required = true
}
```

What do you think?
